INSERT INTO PRODUCTS(PRODUCT_NAME) VALUES('Light Saber');
INSERT INTO PRODUCTS(PRODUCT_NAME) VALUES('Gravity Gun');
INSERT INTO PRODUCTS(PRODUCT_NAME) VALUES('BFG');

INSERT INTO USERS(USER_NAME, USER_PASS) VALUES('SUDO', 'Overlord');
INSERT INTO USERS(USER_NAME, USER_PASS) VALUES('Fallout', 'Vault101');
INSERT INTO USERS(USER_NAME, USER_PASS) VALUES('Sherlock Holmes', 'Nr3');
commit;
