INSERT INTO PRODUCT_DETAILS(PRODUCT_ID, PRODUCT_DESCRIPTION, PRICE) VALUES(1,'An elegant weapon, for a more civilized age', 1000);
INSERT INTO PRODUCT_DETAILS(PRODUCT_ID, PRODUCT_DESCRIPTION, PRICE) VALUES(2,'Float things beacuse it is fun', 3000);
INSERT INTO PRODUCT_DETAILS(PRODUCT_ID, PRODUCT_DESCRIPTION, PRICE) VALUES(3,'Big F*ing Gun', 9001);
commit;
